# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  NCgenJS_config = debug
  NCgenPython_config = debug

else ifeq ($(config),release)
  NCgenJS_config = release
  NCgenPython_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := NCgenJS NCgenPython

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

NCgenJS:
ifneq (,$(NCgenJS_config))
	@echo "==== Building NCgenJS ($(NCgenJS_config)) ===="
	@${MAKE} --no-print-directory -C NCgenPython -f Makefile config=$(NCgenJS_config)
endif

NCgenPython:
ifneq (,$(NCgenPython_config))
	@echo "==== Building NCgenPython ($(NCgenPython_config)) ===="
	@${MAKE} --no-print-directory -C NCgenJS -f Makefile config=$(NCgenPython_config)
endif

clean:
	@${MAKE} --no-print-directory -C NCgenPython -f Makefile clean
	@${MAKE} --no-print-directory -C NCgenJS -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   NCgenJS"
	@echo "   NCgenPython"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"